services:
  bitwarden-to-keepass:
    build: .
    command: ["/bin/bash", "entrypoint.sh"]
    volumes:
      - ./exports:/exports
      - 'bw-config:/root/.config/Bitwarden CLI'
    env_file:
      - .env

volumes:
  bw-config:
